config/routes.rb
Rails.application.routes.draw do
  resources :grade_results
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/grade_result.rb
class GradeResult < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/grade_results_controller.rb
class GradeResultsController < ApplicationController
  before_action :set_grade_result, only: [:show, :edit, :update, :destroy]

  # GET /grade_results
  # GET /grade_results.json
  def index
    @grade_results = GradeResult.all
  end

  # GET /grade_results/1
  # GET /grade_results/1.json
  def show
  end

  # GET /grade_results/new
  def new
    @grade_result = GradeResult.new
  end

  # GET /grade_results/1/edit
  def edit
  end

  # POST /grade_results
  # POST /grade_results.json
  def create
    @grade_result = GradeResult.new(grade_result_params)

    respond_to do |format|
      if @grade_result.save
        format.html { redirect_to @grade_result, notice: 'Grade result was successfully created.' }
        format.json { render :show, status: :created, location: @grade_result }
      else
        format.html { render :new }
        format.json { render json: @grade_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grade_results/1
  # PATCH/PUT /grade_results/1.json
  def update
    respond_to do |format|
      if @grade_result.update(grade_result_params)
        format.html { redirect_to @grade_result, notice: 'Grade result was successfully updated.' }
        format.json { render :show, status: :ok, location: @grade_result }
      else
        format.html { render :edit }
        format.json { render json: @grade_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grade_results/1
  # DELETE /grade_results/1.json
  def destroy
    @grade_result.destroy
    respond_to do |format|
      format.html { redirect_to grade_results_url, notice: 'Grade result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade_result
      @grade_result = GradeResult.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grade_result_params
      params.require(:grade_result).permit(:name, :stundent_id, :score)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grade_results_helper.rb
module GradeResultsHelper
end

app/views/grade_results/_form.html.erb
<%= form_with(model: grade_result, local: true) do |form| %>
  <% if grade_result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grade_result.errors.count, "error") %> prohibited this grade_result from being saved:</h2>

      <ul>
      <% grade_result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :grade_result_name %>
  </div>

  <div class="field">
    <%= form.label :stundentId %>
    <%= form.number_field :stundent_id, id: :grade_result_stundent_id %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.number_field :score, id: :grade_result_score %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/grade_results/edit.html.erb
<h1>Editing Grade Result</h1>

<%= render 'form', grade_result: @grade_result %>

<%= link_to 'Show', @grade_result %> |
<%= link_to 'Back', grade_results_path %>

app/views/grade_results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>成績列表</h1>

<div class="page-header"><%= link_to '新增學生', new_grade_result_path ,class: "btn btn-success" %></div>


<p>分數級別說明 : 90 分以上 S級 / 80~89:A級 /70~79:B級 /60~60:C 未滿60:D級 </p>

<table class="table">
  <thead>
    <tr>
      <th>姓名</th>
      <th>學號</th>
      <th>分數</th>
      <th>處理</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grade_results.each do |grade_result| %>
      <tr>
        <td><%= grade_result.name %></td>
        <td><%= grade_result.stundent_id %></td>
        <td>
          <% case grade_result.score %>
            <% when 90..100 %>
            <%= "S級" %>
            <% when 80..89 %>
            <%= "A級" %>
            <% when 70..79 %>
            <%= "B級" %>
            <% when 60..69 %>
            <%= "C級" %>
            <% else %>
            <%= "D級" %>
          <% end %>
            <%= grade_result.score %>分
          </td>
<!--        <td><%= link_to 'Show', grade_result %></td>-->
        <td><%= link_to '編輯', edit_grade_result_path(grade_result) ,class: "btn btn-success"%></td>
        <td><%= link_to '刪除', grade_result, method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/grade_results/new.html.erb
<h1>New Grade Result</h1>

<%= render 'form', grade_result: @grade_result %>

<%= link_to 'Back', grade_results_path %>

app/views/grade_results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @grade_result.name %>
</p>

<p>
  <strong>Stundent_id:</strong>
  <%= @grade_result.stundent_id %>
</p>

<p>
  <strong>Score:</strong>
  <%= @grade_result.score %>
</p>

<%= link_to 'Edit', edit_grade_result_path(@grade_result) %> |
<%= link_to 'Back', grade_results_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
     <nav class="navbar navbar-default">
          <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">

                <a class="navbar-brand " >國立台北超強大學</a>
                <a ><%= link_to '成績單', grade_results_path, class: "navbar-brand "  %></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->

      </div><!-- /.container-fluid -->
    </nav>
  <head>
    <title>FinalExam</title>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <div class="container">
  
         <%= yield %>
  
     </div>
  </body>
</html>